apiVersion: apps/v1
kind: Deployment 
metadata:
    name: {{ .Values.name | quote }}
    labels:
spec:
    replicas: {{ .Values.replicas }}
    selector:
        matchLabels:
        {{- range $k, $v := .Values.labels }}
            {{ $k }}: {{$v | quote }}
        {{- end }}
    template:
        metadata:
            labels:
            {{- range $k, $v := .Values.labels }}
                {{ $k }}: {{$v}}
            {{- end }}
        spec:
            containers:
                - image: {{ .Values.image }}
                  name: {{ .Values.name }}